### PR TITLE
Update and improve unit test

### PR DESCRIPTION
**Pull request by parkyoora-dev**

### CODE REVIEW

**Review by hasimy-as — CHANGES_REQUESTED** [review]
Merge conflict, pleaaase resolve it first.

**Comment by parkyoora-dev** [comment]
> Merge conflict, pleaaase resolve it first.

Okay I resolve it later, still working on my project😂
Also you still have your sprint review I see ㅋㅋ

**Comment by hasimy-as** [comment]
Done resolve @hasimy-as

**Comment by parkyoora-dev** [comment]
@hasimy-as Review please 😃

**Comment by hasimy-as** [comment]
Okayy nice! @parkyoora-dev

**Pull request merged**
